### ISSUE TITLE
Wiki is broken

### ISSUE THREAD

**Issue by PaddyCube** [mruettgers/SMLReader#43]
Hello,
yesterday, I was able to read through your wiki but today, I'm not. It redirects to start page so it seems it is no longer available. As you did a commit yesterday, I suggest to check if you broken wiki with this.

**Comment by mruettgers** [comment]
Hey,

that sounds strange because I did not use the wiki at all in the past.
Did you mean the README.md?

Michael

**Comment by PaddyCube** [comment]
No I mean the Wiki. If I click on Wiki Link, it redirects me to starting page of this repo
![image](https://user-images.githubusercontent.com/26644498/159002082-ccddb4a4-9e39-4f9a-a805-66ff12dee4ca.png)

**Comment by mruettgers** [comment]
For me it looks like this after clicking the Wiki link:
![Bildschirmfoto 2022-03-18 um 13 35 59](https://user-images.githubusercontent.com/1706429/159004184-79505a7f-6f4f-422a-a074-e05236bc2687.png)

Maybe you are redirected to the repo's starting page because there has no content been added to the Wiki yet?
At least I'm not aware of any content because I never used the Wiki before here.

**Comment by PaddyCube** [comment]
I'm sorry, I mixed-up different repos. Right now, I'm working on a solar tracker which consumes data from smart meter with your SMLReader as well as some data from a PV inverter. It was the repo of PV inverter, which has a wiki explaining the overall structure of used MQTT protocol as well as other instructions.
I thought I've seen similar in your repo, but this isn't true.
